### ISSUE TITLE
ecbuild_check_fortran fails

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/ecbuild#1] opened 2018-06-25 17:25 UTC
I'm trying to build https://github.com/ecmwf/fckit develop so apologies if this is the wrong place to open this, but there is something I am not understanding about the finalization tests performed during the cmake run for fckit, in particular the call:

ecbuild_check_fortran( FEATURES finalization )

I am using an install of a gcc (7.2.0) install in a non-standard place.  The ecbuild command is:

$ecbuild_dir/bin/ecbuild \
  --cmakebin=$cmake_dir/bin/cmake \
  --prefix=$install_dir \
  -DCMAKE_C_COMPILER=$gcc_dir/bin/gcc \
  -DCMAKE_CXX_COMPILER=$gcc_dir/bin/g++ \
  -DCMAKE_CXX_FLAGS="-L$gcc_dir/lib -lgfortran" \
  -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath=$gcc_dir/lib64" \
  -DCMAKE_Fortran_COMPILER=$gcc_dir/bin/gfortran \
  -DCMAKE_Fortran_FLAGS="-L$gcc_dir/lib -lstdc++" \
  -DCMAKE_MODULE_PATH=$ecbuild_dir/share/ecbuild/cmake \
  -DECKIT_PATH="$eckit_dir" \
  -DMPIEXEC=$mpich_dir/bin/mpiexec \

The CMAKE_EXE_LINKER_FLAGS are necessary to avoid runtime failures due to missing libgfortran.  The ecbuild version is 2.9.0, cmake version is 3.11.1.  The output for the Fortran finalization is:

-- Checking Fortran support for "finalization"
-- Checking Fortran support for "finalization" -- not supported
-- Feature FINAL was not enabled (also not requested) -- following condition was not met: EC_HAVE_Fortran_FINALIZATION
-- FCKIT_HAVE_FINAL [0]

I looked further into it though and it appears that the test executable isn't being compiled correctly and hence is failing due to the missing libgfortran error mentioned above.  I inserted some message commands in ecbuild_try_run.cmake:

_compile_out = Change Dir: /data/local/frwd/extractions/fckit/ecmwf-develop/build-dir/fortran_feature_tests/fortran_finalization/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_7d145/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_7d145.dir/build.make CMakeFiles/cmTC_7d145.dir/build
gmake[1]: Entering directory `/data/local/frwd/extractions/fckit/ecmwf-develop/build-dir/fortran_feature_tests/fortran_finalization/CMakeFiles/CMakeTmp'
Building Fortran object CMakeFiles/cmTC_7d145.dir/finalization.F90.o
/project/ukmo/rhel6/fortran/opt/gfortran/packages/gcc/7.2.0/bin/gfortran   -L/project/ukmo/rhel6/fortran/opt/gfortran/packages/gcc/7.2.0/lib -lstdc++  -fPIE   -c /data/users/frwd/installs/ecbuild/gnu/ecmwf-develop/share/ecbuild/cmake/fortran_features/finalization.F90 -o CMakeFiles/cmTC_7d145.dir/finalization.F90.o
Linking Fortran executable cmTC_7d145
/net/data/nwp1/frwd/installs/cmake/3.11.1/v1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7d145.dir/link.txt --verbose=1
/project/ukmo/rhel6/fortran/opt/gfortran/packages/gcc/7.2.0/bin/gfortran    -L/project/ukmo/rhel6/fortran/opt/gfortran/packages/gcc/7.2.0/lib -lstdc++  CMakeFiles/cmTC_7d145.dir/finalization.F90.o  -o cmTC_7d145 
gmake[1]: Leaving directory `/data/local/frwd/extractions/fckit/ecmwf-develop/build-dir/fortran_feature_tests/fortran_finalization/CMakeFiles/CMakeTmp'

....

_run_res = 127
_run_out = 
_run_err = /data/local/frwd/extractions/fckit/ecmwf-develop/build-dir//data/users/frwd/installs/ecbuild/gnu/ecmwf-develop/share/ecbuild/cmake/fortran_features/finalization.F90.bin: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory

So the compile works but the run fails due to the shared library not being found; this is because the RPATH has not been set.

As a workaround I can set the -rpath=... option in the CMAKE_Fortran_FLAGS; it appears that this propagates to ecbuild_check_fortran.  But surely CMAKE_EXE_LINKER_FLAGS should as well?

**Comment by wdeconinck** [comment] 2018-06-28 10:31
Dear @DJDavies2 
I'm not sure if this is related to ecbuild or fckit but rather the linker not adding the gcc library directory in the rpath automatically. This could be a misconfigured compiler installation.
I'm not sure how CMake handles the rpath in `try_compile()`
You could set `LD_LIBRARY_PATH` to overcome this during compilation.
The `CMAKE_EXE_LINKER_FLAGS` trick may work for the executables using `ecbuild_add_executable()` to include the rpath.

**Comment by DJDavies2** [comment] 2018-07-03 10:34
It is true that the linker isn't adding the gcc runtime libraries automatically but this is a custom build of gcc in a non-standard location so the linker won't know where they are unless it is told.  This particular problem is that the executables compiled by fortran_finalization test doesn't have its rpath or runpath set; this is normal documented behaviour for gcc:

https://gcc.gnu.org/faq.html#rpath

I'm not very familiar with try_compile, but looking at https://cmake.org/cmake/help/v3.0/command/try_compile.html it seems that stuff is not passed by default but can be passed if appropriate.

I think ecbuild_add_executable already handles CMAKE_EXE_LINKER_FLAGS correctly, there is no problem with the proper executables once the Fortran finalisation test is survived.  It is just the test executables that are choosing not to use it.

Setting LD_LIBRARY_PATH might work but there is a more general point here isn't there?  Surely the whole point of these compilation tests is that they test the compile system that will actually be used to generate the executables?  As things stand that is not happening, it is testing a different compilation system and as such the results of it are irrelevant and there is little point doing the test at all.  There are many situations where particular features depend on specific compile or link options (e.g. options to set standards conformance levels, or e.g. openmp support that depends on linking specific runtime libraries).

**Comment by tlmquintino** [comment] 2018-07-03 12:02
@wdeconinck maybe it would be if `fortran_feature_check()` only uses `try_compile()` instead of `try_run()`.  If I understand the requirement is to test if the compiler supports `final` but the issue is at runtime.  

It would also make that function work with cross compilation without have a separate branch for that.

**Comment by wdeconinck** [comment] 2018-07-12 14:01
I'm happy with PR #2 to be merged in

**Closed** 2018-07-23 18:40 UTC
